-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "height" DOUBLE PRECISION NOT NULL DEFAULT 4,
ADD COLUMN     "length" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN     "weight" DOUBLE PRECISION NOT NULL DEFAULT 0.3,
ADD COLUMN     "width" DOUBLE PRECISION NOT NULL DEFAULT 20;
